# Generated by Django 3.1.2 on 2022-04-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alarmas_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen_principal', models.ImageField(upload_to='images/alarmas')),
                ('imagen_frente', models.ImageField(blank=True, null=True, upload_to='images/alarmas')),
                ('imagen_izquierda', models.ImageField(blank=True, null=True, upload_to='images/alarmas')),
                ('imagen_derecha', models.ImageField(blank=True, null=True, upload_to='images/alarmas')),
                ('imagen_trasera', models.ImageField(blank=True, null=True, upload_to='images/alarmas')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('precio_producto', models.PositiveIntegerField()),
                ('precio_producto_servicio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='camaras_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen_principal', models.ImageField(upload_to='images/camaras')),
                ('imagen_frente', models.ImageField(blank=True, null=True, upload_to='images/camaras')),
                ('imagen_izquierda', models.ImageField(blank=True, null=True, upload_to='images/camaras')),
                ('imagen_derecha', models.ImageField(blank=True, null=True, upload_to='images/camaras')),
                ('imagen_trasera', models.ImageField(blank=True, null=True, upload_to='images/camaras')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('precio_producto', models.PositiveIntegerField()),
                ('precio_producto_servicio', models.PositiveIntegerField()),
                ('tipo', models.IntegerField(choices=[(0, 'Bullet'), (1, 'Domo'), (2, 'Domo motorizadas'), (3, 'Minicamaras'), (4, 'Camufladas')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='detectores_incendio_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen_principal', models.ImageField(upload_to='images/alarmas')),
                ('imagen_frente', models.ImageField(blank=True, null=True, upload_to='images/detectores_incendio')),
                ('imagen_izquierda', models.ImageField(blank=True, null=True, upload_to='images/detectores_incendio')),
                ('imagen_derecha', models.ImageField(blank=True, null=True, upload_to='images/detectores_incendio')),
                ('imagen_trasera', models.ImageField(blank=True, null=True, upload_to='images/detectores_incendio')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('precio_producto', models.PositiveIntegerField()),
                ('precio_producto_servicio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='grabadores_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen_principal', models.ImageField(upload_to='images/grabadores')),
                ('imagen_frente', models.ImageField(blank=True, null=True, upload_to='images/grabadores')),
                ('imagen_izquierda', models.ImageField(blank=True, null=True, upload_to='images/grabadores')),
                ('imagen_derecha', models.ImageField(blank=True, null=True, upload_to='images/grabadores')),
                ('imagen_trasera', models.ImageField(blank=True, null=True, upload_to='images/grabadores')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('precio_producto', models.PositiveIntegerField()),
                ('precio_producto_servicio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='informacion_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=1000)),
                ('titulo_informacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('dato_1', models.TextField(blank=True, null=True)),
                ('dato_2', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='informacion_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=1000)),
                ('titulo_informacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('descripcion_informacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='informacion_instalaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=1000)),
                ('titulo_informacion', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion_informacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nueva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='otras_empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
